# Generated by Django 4.2.1 on 2023-06-01 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.IntegerField(max_length=10)),
                ('adresse', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('contact', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.IntegerField(max_length=10)),
                ('adresse', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('date_naissance', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agence')),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('IBAN', models.CharField(max_length=100)),
                ('solde', models.FloatField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Demandes_ouvertures_comptes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.IntegerField(max_length=10, unique=True)),
                ('document_pic', models.ImageField(upload_to='passport_pic')),
                ('photo', models.ImageField(upload_to='photo')),
            ],
        ),
        migrations.CreateModel(
            name='Virement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.beneficiaire')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.compte')),
            ],
        ),
        migrations.CreateModel(
            name='Transcation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('montant', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.compte')),
            ],
        ),
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('operateur', models.CharField(max_length=30)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.compte')),
            ],
        ),
        migrations.CreateModel(
            name='Rechargement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('operateur', models.CharField(max_length=30)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.compte')),
            ],
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=100)),
                ('num_facture', models.IntegerField(max_length=10)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.compte')),
            ],
        ),
        migrations.CreateModel(
            name='Demandes_chequiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Demandes_cartes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Demandes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Chequier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_page', models.IntegerField(max_length=3)),
                ('date_expiration', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.compte')),
            ],
        ),
        migrations.CreateModel(
            name='Carte_credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('date_expiration', models.DateField()),
                ('cvv', models.IntegerField(max_length=3)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.compte')),
            ],
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client'),
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('date_naissance', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agence')),
            ],
        ),
    ]
