# Generated by Django 4.2.1 on 2023-06-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_carte_credit_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte_credit',
            name='cvv',
            field=models.IntegerField(max_length=3),
        ),
    ]
