# Generated by Django 4.2.1 on 2023-06-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_phonemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='code_secret',
            field=models.CharField(default=2907, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='key',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
