# Generated by Django 4.2.1 on 2023-06-08 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_phonemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='key',
        ),
    ]
