# Generated by Django 4.2.1 on 2023-06-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_photo_demandes_ouvertures_comptes_user_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandes_ouvertures_comptes',
            name='code_secret',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
