# Generated by Django 4.2.1 on 2023-06-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_demandes_ouvertures_comptes_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandes_ouvertures_comptes',
            name='user_pic',
            field=models.ImageField(upload_to='user_pic'),
        ),
    ]
