# Generated by Django 4.2.1 on 2023-06-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_demandes_ouvertures_comptes_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandes_ouvertures_comptes',
            name='date_naissance',
            field=models.DateField(),
        ),
    ]
