# Generated by Django 4.2.1 on 2023-06-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_demandes_ouvertures_comptes_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandes_ouvertures_comptes',
            name='contact',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='demandes_ouvertures_comptes',
            name='date_naissance',
            field=models.DateField(blank=True),
        ),
    ]
