# Generated by Django 4.2.1 on 2023-06-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_demandes_ouvertures_comptes_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandes_ouvertures_comptes',
            name='user_pic',
        ),
        migrations.AddField(
            model_name='demandes_ouvertures_comptes',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo'),
        ),
    ]
