# Generated by Django 4.2.1 on 2023-06-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_demandes_ouvertures_comptes_user_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaire',
            name='contact',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
