# Generated by Django 4.2.1 on 2023-06-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_beneficiaire_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcation',
            name='type',
        ),
    ]
