# Generated by Django 4.2.1 on 2023-06-13 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_transaction_delete_transcation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('montant', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('operateur', models.CharField(max_length=30)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.compte')),
            ],
        ),
        migrations.RemoveField(
            model_name='rechargement',
            name='compte',
        ),
        migrations.RemoveField(
            model_name='retrait',
            name='compte',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='compte',
        ),
        migrations.RenameField(
            model_name='virement',
            old_name='compte',
            new_name='compte_beneficiaire',
        ),
        migrations.RemoveField(
            model_name='virement',
            name='beneficiaire',
        ),
        migrations.AddField(
            model_name='virement',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agence',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carte_credit',
            name='cvv',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payement',
            name='num_facture',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payement',
            name='type',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Demandes',
        ),
        migrations.DeleteModel(
            name='Rechargement',
        ),
        migrations.DeleteModel(
            name='Retrait',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
