# Generated by Django 4.2.1 on 2023-06-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_operations_remove_rechargement_compte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequier',
            name='num_page',
            field=models.IntegerField(),
        ),
    ]
