# Generated by Django 4.2.1 on 2023-06-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_chequier_num_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payement',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
