# Generated by Django 4.2.1 on 2023-06-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_payement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte_credit',
            name='date_expiration',
            field=models.CharField(max_length=8),
        ),
    ]
