# Generated by Django 4.2.1 on 2023-06-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_conversation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.IntegerField(choices=[(0, 'Client'), (1, 'Agent')]),
        ),
    ]
