# Generated by Django 4.2.1 on 2023-06-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='type',
            field=models.IntegerField(choices=[(0, 'Retrait'), (1, 'Dépôt')]),
        ),
    ]
